-- Template only.
-- Isi nilai R2 dari local lalu jalankan ke live jika tidak ingin memakai script Node.
-- Query ini hanya menyentuh 5 field R2 dan tidak mengubah field AppConfig lain.

INSERT INTO "AppConfig" (
  "id",
  "aiAutoReplyEnabled",
  "aiApiUrl",
  "aiApiKey",
  "aiModel",
  "promptSystem",
  "waApiUrl",
  "waSessionId",
  "waToken",
  "waMasterKey",
  "mongodbUri",
  "mongodbDb",
  "ragCollection",
  "ragIndexName",
  "embeddingProvider",
  "embeddingApiKey",
  "embeddingModel",
  "embeddingDimensions",
  "embeddingBaseUrl",
  "bytePlusApiKey",
  "bytePlusBaseUrl",
  "bytePlusImageModel",
  "r2AccessKey",
  "r2SecretKey",
  "r2Bucket",
  "r2Endpoint",
  "r2PublicUrl",
  "topicScoutSearchApiKey",
  "topicScoutSearchUrl",
  "topicScoutModelApiKey",
  "topicScoutModelBaseUrl",
  "topicScoutModel",
  "topicScoutDefaultQuery",
  "metaAppId",
  "metaAppSecret",
  "metaGraphVersion",
  "metaFacebookPageId",
  "metaFacebookPageName",
  "metaInstagramBusinessId",
  "metaInstagramUsername",
  "metaPageAccessToken",
  "metaPageTokenExpiresAt",
  "threadsUserId",
  "threadsUsername",
  "threadsAccessToken",
  "threadsTokenExpiresAt",
  "threadsApiVersion",
  "threadsApiBaseUrl",
  "linkedinClientId",
  "linkedinClientSecret",
  "linkedinRedirectUri",
  "linkedinAccessToken",
  "linkedinRefreshToken",
  "linkedinTokenExpiresAt",
  "linkedinAuthorUrn",
  "linkedinOrganizationUrn",
  "linkedinApiVersion",
  "autoPostEnabled",
  "schedulerSecret",
  "createdAt",
  "updatedAt"
) VALUES (
  1,
  true,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'PASTE_LOCAL_R2_ACCESS_KEY',
  'PASTE_LOCAL_R2_SECRET_KEY',
  'PASTE_LOCAL_R2_BUCKET',
  'PASTE_LOCAL_R2_ENDPOINT',
  'PASTE_LOCAL_R2_PUBLIC_URL',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'v23.0',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'v1.0',
  'https://graph.threads.net',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '202504',
  false,
  '',
  NOW(),
  NOW()
)
ON CONFLICT ("id") DO UPDATE SET
  "r2AccessKey" = EXCLUDED."r2AccessKey",
  "r2SecretKey" = EXCLUDED."r2SecretKey",
  "r2Bucket" = EXCLUDED."r2Bucket",
  "r2Endpoint" = EXCLUDED."r2Endpoint",
  "r2PublicUrl" = EXCLUDED."r2PublicUrl",
  "updatedAt" = NOW();
