-- Replace placeholder values before executing on a live environment.
INSERT INTO "AppConfig" (
  "id",
  "aiApiUrl",
  "aiApiKey",
  "aiModel",
  "promptSystem",
  "waApiUrl",
  "waSessionId",
  "waToken",
  "waMasterKey",
  "mongodbUri",
  "mongodbDb",
  "ragCollection",
  "ragIndexName",
  "embeddingProvider",
  "embeddingApiKey",
  "embeddingModel",
  "embeddingDimensions",
  "embeddingBaseUrl",
  "bytePlusApiKey",
  "bytePlusBaseUrl",
  "bytePlusImageModel",
  "topicScoutSearchApiKey",
  "topicScoutSearchUrl",
  "topicScoutModelApiKey",
  "topicScoutModelBaseUrl",
  "topicScoutModel",
  "topicScoutDefaultQuery",
  "metaAppId",
  "metaAppSecret",
  "metaGraphVersion",
  "metaFacebookPageId",
  "metaFacebookPageName",
  "metaInstagramBusinessId",
  "metaInstagramUsername",
  "metaPageAccessToken",
  "metaPageTokenExpiresAt",
  "threadsUserId",
  "threadsUsername",
  "threadsAccessToken",
  "threadsTokenExpiresAt",
  "threadsApiVersion",
  "threadsApiBaseUrl",
  "linkedinClientId",
  "linkedinClientSecret",
  "linkedinRedirectUri",
  "linkedinAccessToken",
  "linkedinRefreshToken",
  "linkedinTokenExpiresAt",
  "linkedinAuthorUrn",
  "linkedinOrganizationUrn",
  "linkedinApiVersion",
  "autoPostEnabled",
  "schedulerSecret",
  "createdAt",
  "updatedAt"
) VALUES (
  1,
  'https://ai.sumopod.com/v1/chat/completions',
  'sk-xxxx',
  'seed-2-0-mini',
  $$Kamu adalah AI WhatsApp untuk bisnis.

Tugas kamu:
- Menjawab pertanyaan customer
- Memberikan info produk / layanan
- Membantu closing ringan

Style:
- Ramah, cepat, to the point
- Tidak terlalu panjang
- Gunakan emoji secukupnya
- Bahasa Indonesia santai profesional

Jika tidak tahu:
-> arahkan ke admin

Jika ditanya harga:
-> jawab + ajak lanjut$$,
  'https://waflash.citradigitalhotel.it.com/api/v1',
  'alphaprod',
  'ISI_SENDIRI',
  'ISI_SENDIRI',
  'mongodb+srv://user:pass@cluster.mongodb.net/',
  'wa_ai_db',
  'knowledge',
  'vector_index',
  'mongodb',
  'ISI_SENDIRI',
  'voyage-4-large',
  '1024',
  'https://ai.mongodb.com/v1',
  'ISI_SENDIRI',
  'https://ark.ap-southeast.bytepluses.com/api/v3',
  'seedream-4-5-251128',
  'ISI_SENDIRI',
  'https://search.infoquest.bytepluses.com',
  'ISI_SENDIRI',
  'https://ark.ap-southeast.bytepluses.com/api/v3',
  'seed-2-0-mini-260215',
  'tren terbaru hotel indonesia direct booking OTA website hotel AI customer service hospitality marketing',
  'ISI_SENDIRI',
  'ISI_SENDIRI',
  'v25.0',
  'ISI_SENDIRI',
  'Nama Halaman Facebook',
  'ISI_SENDIRI',
  'username_instagram',
  'ISI_SENDIRI',
  '',
  'ISI_SENDIRI',
  'username_threads',
  'ISI_SENDIRI',
  '',
  'v1.0',
  'https://graph.threads.net',
  'ISI_SENDIRI',
  'ISI_SENDIRI',
  'https://jakacs.arahdigital.id/api/social/linkedin/callback',
  '',
  '',
  '',
  '',
  '',
  '202504',
  false,
  'change-this-secret',
  NOW(),
  NOW()
) ON CONFLICT ("id") DO UPDATE SET
  "aiApiUrl" = EXCLUDED."aiApiUrl",
  "aiApiKey" = EXCLUDED."aiApiKey",
  "aiModel" = EXCLUDED."aiModel",
  "promptSystem" = EXCLUDED."promptSystem",
  "waApiUrl" = EXCLUDED."waApiUrl",
  "waSessionId" = EXCLUDED."waSessionId",
  "waToken" = EXCLUDED."waToken",
  "waMasterKey" = EXCLUDED."waMasterKey",
  "mongodbUri" = EXCLUDED."mongodbUri",
  "mongodbDb" = EXCLUDED."mongodbDb",
  "ragCollection" = EXCLUDED."ragCollection",
  "ragIndexName" = EXCLUDED."ragIndexName",
  "embeddingProvider" = EXCLUDED."embeddingProvider",
  "embeddingApiKey" = EXCLUDED."embeddingApiKey",
  "embeddingModel" = EXCLUDED."embeddingModel",
  "embeddingDimensions" = EXCLUDED."embeddingDimensions",
  "embeddingBaseUrl" = EXCLUDED."embeddingBaseUrl",
  "bytePlusApiKey" = EXCLUDED."bytePlusApiKey",
  "bytePlusBaseUrl" = EXCLUDED."bytePlusBaseUrl",
  "bytePlusImageModel" = EXCLUDED."bytePlusImageModel",
  "topicScoutSearchApiKey" = EXCLUDED."topicScoutSearchApiKey",
  "topicScoutSearchUrl" = EXCLUDED."topicScoutSearchUrl",
  "topicScoutModelApiKey" = EXCLUDED."topicScoutModelApiKey",
  "topicScoutModelBaseUrl" = EXCLUDED."topicScoutModelBaseUrl",
  "topicScoutModel" = EXCLUDED."topicScoutModel",
  "topicScoutDefaultQuery" = EXCLUDED."topicScoutDefaultQuery",
  "metaAppId" = EXCLUDED."metaAppId",
  "metaAppSecret" = EXCLUDED."metaAppSecret",
  "metaGraphVersion" = EXCLUDED."metaGraphVersion",
  "metaFacebookPageId" = EXCLUDED."metaFacebookPageId",
  "metaFacebookPageName" = EXCLUDED."metaFacebookPageName",
  "metaInstagramBusinessId" = EXCLUDED."metaInstagramBusinessId",
  "metaInstagramUsername" = EXCLUDED."metaInstagramUsername",
  "metaPageAccessToken" = EXCLUDED."metaPageAccessToken",
  "metaPageTokenExpiresAt" = EXCLUDED."metaPageTokenExpiresAt",
  "threadsUserId" = EXCLUDED."threadsUserId",
  "threadsUsername" = EXCLUDED."threadsUsername",
  "threadsAccessToken" = EXCLUDED."threadsAccessToken",
  "threadsTokenExpiresAt" = EXCLUDED."threadsTokenExpiresAt",
  "threadsApiVersion" = EXCLUDED."threadsApiVersion",
  "threadsApiBaseUrl" = EXCLUDED."threadsApiBaseUrl",
  "linkedinClientId" = EXCLUDED."linkedinClientId",
  "linkedinClientSecret" = EXCLUDED."linkedinClientSecret",
  "linkedinRedirectUri" = EXCLUDED."linkedinRedirectUri",
  "linkedinAccessToken" = EXCLUDED."linkedinAccessToken",
  "linkedinRefreshToken" = EXCLUDED."linkedinRefreshToken",
  "linkedinTokenExpiresAt" = EXCLUDED."linkedinTokenExpiresAt",
  "linkedinAuthorUrn" = EXCLUDED."linkedinAuthorUrn",
  "linkedinOrganizationUrn" = EXCLUDED."linkedinOrganizationUrn",
  "linkedinApiVersion" = EXCLUDED."linkedinApiVersion",
  "autoPostEnabled" = EXCLUDED."autoPostEnabled",
  "schedulerSecret" = EXCLUDED."schedulerSecret",
  "updatedAt" = NOW();
